version: "3.8"

services:
  halo-go:
    image: halohub/halo-go:latest
    container_name: halo-go
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - ~/.halo2:/data
    environment:
      - GIN_MODE=release

  halo-java:
    image: halohub/halo:2
    container_name: halo-java
    restart: always
    ports:
      - "8091:8090"
    volumes:
      - ~/.halo2-java:/root/.halo2
    environment:
      - JVM_OPTS=-Xmx256m -Xms256m