name: Halo CI/CD

on:
  push:
    branches:
      - build
  # schedule:
  #   - cron: "30 1 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  issues: write
  id-token: write

jobs:
  ci:
    runs-on:
      - self-hosted
      - linux
      - x64
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        if: github.event_name == 'push'
        uses: pnpm/action-setup@v3
        with:
          version: "10"

      - name: Set up Node.js
        if: github.event_name == 'push'
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: "ui/pnpm-lock.yaml"

      - name: Setup JDK
        if: github.event_name == 'push'
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          cache: "gradle"
          java-version: "21"

      - name: Build Halo
        if: github.event_name == 'push'
        run: ./gradlew clean downloadPluginPresets build -x check --configuration-cache --configuration-cache-problems=warn

      - name: Docker meta for Halo
        if: github.event_name == 'push'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/halo-dev
            ${{ secrets.DOCKERHUB_USERNAME }}/halo-dev
          tags: |
            type=ref,event=branch
            type=sha
          flavor: |
            latest=false

      - name: Set up QEMU
        if: github.event_name == 'push'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true

      - name: Install Dependencies for UI
        if: github.event_name == 'push'
        run: ./gradlew pnpmInstall

      - name: Build UI Packages
        if: github.event_name == 'push'
        run: cd ui && pnpm build:packages

      - name: Release UI Packages
        if: github.event_name == 'push'
        run: cd ui && pnpx pkg-pr-new publish --compact --pnpm './packages/*'

      - name: Close Stale Issues
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        uses: actions/stale@v10
        with:
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity.
            It will be closed if no further activity occurs within the next 2 days.
            If you believe this issue is still relevant, please provide the requested information.
          close-issue-message: |
            This issue has been automatically closed due to inactivity.
            If you have the requested information, feel free to reopen it or create a new issue.
          days-before-issue-stale: 60
          days-before-issue-close: 2
          days-before-pr-stale: -1
          days-before-pr-close: -1
          stale-issue-label: "lifecycle/stale"
          any-of-issue-labels: "triage/needs-information,priority/awaiting-more-evidence,help wanted"
          operations-per-run: 100
          ascending: true
